### ISSUE TITLE
Load TSV files into Tensorboard

### ISSUE THREAD

**Issue by ghost** [parulsethi/DocViz#1]
How did you actually get the TSV files to show up in a locally run version of Tensorboard? I have the same folder structure as you (including the embeddings json file), but running Tensorboard results in "No dashboards are active for the current data set.".

**Comment by parulsethi** [comment]
Hi @cameronwtaylor 

I only used the online [Tensorboard projector](http://projector.tensorflow.org/) on which we can upload our TSV files using the `Load Data` button on the left panel. 

However, for the local version of Tensorboard, you might find this [code snippet](https://github.com/ArdalanM/gensim2tensorboard/blob/master/src/models.py#L104)(create_embeddings() function) helpful in which the embeddings are directly stored in a log directory which is used as input for the local version of Tensorboard.
